# Generated by Django 4.1.3 on 2022-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_familiar_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha',
            field=models.DateField(default=True),
        ),
    ]
