# Generated by Django 4.1.3 on 2022-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('animal', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=True)),
            ],
        ),
    ]
